"""End-to-end tests for the Text-to-SQL RAG chat pipeline.

The RAG service (``app/services/rag.py``) is the single data-querying path for
the AI Chat. These tests run the full pipeline offline with a stubbed LLM and
stubbed supabase-mcp query tools:

    describe schema -> rank tables -> generate SQL -> read-only guard ->
    scoped execution -> natural-language answer.

Execution is stubbed at the tool boundary, so these tests assert what the
pipeline *sends* to supabase-mcp. The tool's own org-scoping enforcement is
covered separately in ``tests/test_supabase_query_tools.py``.
"""

from unittest.mock import patch

import pytest

from app.mcp.supabase.tools_query import ScopeError
from app.services import rag

TABLE_SPECS = [
    "CREATE TABLE unified_transactions (\n  id integer,\n  user_id integer,\n"
    "  category text,\n  amount numeric,\n  transaction_date date\n);"
]


def _stub_pipeline(monkeypatch, fake_generate_text, history=None, rows=None):
    """Wire the RAG pipeline to stubbed supabase-mcp tools + a stubbed LLM."""
    seen: dict = {}

    async def fake_describe(user_id, table_name="unified_transactions"):
        return TABLE_SPECS

    async def fake_run(user_id, sql, max_rows=None):
        seen["sql"] = sql
        return {"rows": rows if rows is not None else [], "row_count": 0, "truncated": False}

    monkeypatch.setattr(rag, "describe_table", fake_describe)
    monkeypatch.setattr(rag, "run_read_only_sql", fake_run)
    monkeypatch.setattr(rag, "get_user_settings", lambda user_id: {"llm_primary_provider": "mock", "api_key": ""})
    monkeypatch.setattr(rag, "get_user_chat_history", lambda user_id, limit=10: history or [])
    monkeypatch.setattr(rag, "get_domain_user_ids", lambda user_id: [user_id])
    monkeypatch.setattr(rag, "JINA_API_KEY", "")
    seen["rows"] = rows
    return patch("app.services.llm_factory.generate_text", fake_generate_text), seen


async def _realistic_llm(model, prompt: str) -> str:
    """Stub LLM: writes SQL for the schema prompt, answers for the response prompt."""
    if "Generate a SQL query" in prompt:
        return (
            "SELECT user_id, category, SUM(amount) AS total "
            "FROM unified_transactions WHERE transaction_type = 'expense' GROUP BY category"
        )
    return "Total expense by category: Marketing $1200, Payroll $5000."


# --------------------------------------------------------------------------- #
# Pipeline pieces
# --------------------------------------------------------------------------- #
@pytest.mark.anyio
async def test_schema_comes_from_supabase_mcp(monkeypatch):
    async def fake_describe(user_id, table_name="unified_transactions"):
        assert table_name == "unified_transactions"
        return TABLE_SPECS

    monkeypatch.setattr(rag, "describe_table", fake_describe)
    specs = await rag._describe_chat_tables(1)
    assert "CREATE TABLE unified_transactions" in specs[0]


@pytest.mark.anyio
async def test_rank_tables_returns_unranked_without_key(monkeypatch):
    monkeypatch.setattr(rag, "JINA_API_KEY", "")
    specs = ["CREATE TABLE transactions (id int);", "CREATE TABLE user_settings (id int);"]
    ranked = await rag.rank_tables("marketing spend", specs)
    assert len(ranked) == 2
    assert all(score == 0.0 for score, _ in ranked)


@pytest.mark.anyio
async def test_rag_never_opens_a_connection(monkeypatch):
    """The RAG service must not hold a DB connection; retrieval is MCP-only."""

    def explode():
        raise AssertionError("RAG must not open a database connection")

    monkeypatch.setattr(rag, "get_connection", explode, raising=False)
    fake_rows = [{"category": "Marketing", "total": 1200}]
    patcher, _ = _stub_pipeline(monkeypatch, _realistic_llm, rows=fake_rows)
    with patcher:
        answer = await rag.answer_with_rag(user_id=1, question="How much did we spend on Marketing?")
    assert "Marketing $1200" in answer


# --------------------------------------------------------------------------- #
# End-to-end
# --------------------------------------------------------------------------- #
@pytest.mark.anyio
async def test_rag_pipeline_end_to_end(monkeypatch):
    """Full pipeline: schema -> SQL -> scoped execution -> grounded answer."""
    fake_rows = [
        {"category": "Marketing", "total": 1200},
        {"category": "Payroll", "total": 5000},
    ]
    patcher, seen = _stub_pipeline(monkeypatch, _realistic_llm, rows=fake_rows)
    with patcher:
        answer = await rag.answer_with_rag(user_id=1, question="How much did we spend on Marketing?")
    assert "Marketing $1200" in answer
    # The SQL reached the org-scoped tool, not a local connection.
    assert "unified_transactions" in seen["sql"]


@pytest.mark.anyio
async def test_rag_pipeline_rejects_mutating_sql(monkeypatch):
    """A non-SELECT query generated by the LLM must be refused before execution."""

    async def _bad_sql(model, prompt: str) -> str:
        return "DELETE FROM unified_transactions"

    patcher, _ = _stub_pipeline(monkeypatch, _bad_sql)
    with patcher:
        answer = await rag.answer_with_rag(user_id=1, question="delete everything")
    assert "read-only" in answer


@pytest.mark.anyio
async def test_rag_pipeline_rejects_chained_statements(monkeypatch):
    """Multi-statement payloads must be refused even if they start with SELECT."""

    async def _chained_sql(model, prompt: str) -> str:
        return "SELECT * FROM unified_transactions; DROP TABLE unified_transactions"

    patcher, _ = _stub_pipeline(monkeypatch, _chained_sql)
    with patcher:
        answer = await rag.answer_with_rag(user_id=1, question="anything")
    assert "read-only" in answer


@pytest.mark.anyio
async def test_stream_endpoint_path_streams_the_same_answer(monkeypatch):
    """The streaming entry point (/api/chat/data-query/stream) shares the pipeline."""
    fake_rows = [{"category": "Marketing", "total": 1200}]

    async def fake_stream(model, prompt: str):
        for chunk in ("Marketing ", "$1200."):
            yield chunk

    patcher, _ = _stub_pipeline(monkeypatch, _realistic_llm, rows=fake_rows)
    with patcher, patch("app.services.llm_factory.generate_text_stream", fake_stream):
        chunks = [c async for c in rag.answer_with_rag_stream(1, "How much did we spend on Marketing?")]

    assert "".join(chunks) == "Marketing $1200."


@pytest.mark.anyio
async def test_stream_yields_abort_message(monkeypatch):
    async def _bad_sql(model, prompt: str) -> str:
        return "DROP TABLE unified_transactions"

    patcher, _ = _stub_pipeline(monkeypatch, _bad_sql)
    with patcher:
        chunks = [c async for c in rag.answer_with_rag_stream(1, "nope")]

    assert "read-only" in "".join(chunks)


# --------------------------------------------------------------------------- #
# Scoping retry
# --------------------------------------------------------------------------- #
@pytest.mark.anyio
async def test_scope_error_triggers_one_regeneration(monkeypatch):
    """A projection without user_id is recovered by regenerating the SQL once."""
    calls = {"n": 0}

    async def _flaky_sql(model, prompt: str) -> str:
        if "Generate a SQL query" in prompt:
            calls["n"] += 1
            if calls["n"] == 1:
                return "SELECT SUM(amount) AS total FROM unified_transactions"
            assert "user_id column" in prompt
            return "SELECT user_id, SUM(amount) AS total FROM unified_transactions"
        return "Total: $6200."

    async def fake_describe(user_id, table_name="unified_transactions"):
        return TABLE_SPECS

    async def fake_run(user_id, sql, max_rows=None):
        if "user_id" not in sql:
            raise ScopeError("query must include user_id in its SELECT list")
        return {"rows": [{"total": 6200}], "row_count": 1, "truncated": False}

    monkeypatch.setattr(rag, "describe_table", fake_describe)
    monkeypatch.setattr(rag, "run_read_only_sql", fake_run)
    monkeypatch.setattr(rag, "get_user_settings", lambda uid: {"llm_primary_provider": "mock", "api_key": ""})
    monkeypatch.setattr(rag, "get_user_chat_history", lambda uid, limit=10: [])
    monkeypatch.setattr(rag, "get_domain_user_ids", lambda uid: [uid])
    monkeypatch.setattr(rag, "JINA_API_KEY", "")

    with patch("app.services.llm_factory.generate_text", _flaky_sql):
        answer = await rag.answer_with_rag(user_id=1, question="Total spend?")

    assert calls["n"] == 2
    assert "Total: $6200." in answer


# --------------------------------------------------------------------------- #
# Conversation history context
# --------------------------------------------------------------------------- #
@pytest.mark.anyio
async def test_conversation_history_injected_into_sql_prompt(monkeypatch):
    """History messages must appear in the SQL generation prompt."""
    captured_prompts = []

    async def _capture_llm(model, prompt: str) -> str:
        captured_prompts.append(prompt)
        if "Generate a SQL query" in prompt:
            return "SELECT user_id, category, SUM(amount) AS total FROM unified_transactions GROUP BY category"
        return "Total expense by category: Marketing $1200."

    fake_history = [
        {"sender": "user", "text": "What were our top expenses?"},
        {"sender": "agent", "text": "Our top expenses were Payroll ($5000) and Marketing ($1200)."},
    ]

    patcher, _ = _stub_pipeline(
        monkeypatch, _capture_llm, history=fake_history, rows=[{"category": "Marketing", "total": 1200}]
    )
    with patcher:
        answer = await rag.answer_with_rag(user_id=1, question="What about Payroll?")

    sql_prompt = captured_prompts[0]
    assert "=== CONVERSATION HISTORY ===" in sql_prompt
    assert "What were our top expenses?" in sql_prompt
    assert "Our top expenses were Payroll" in sql_prompt
    assert "=== END HISTORY ===" in sql_prompt
    assert "What about Payroll?" in sql_prompt
    assert answer  # got a response


@pytest.mark.anyio
async def test_conversation_history_injected_into_response_prompt(monkeypatch):
    """History messages must also appear in the natural-language response prompt."""
    captured_prompts = []

    async def _capture_llm(model, prompt: str) -> str:
        captured_prompts.append(prompt)
        if "Generate a SQL query" in prompt:
            return "SELECT user_id, category, SUM(amount) AS total FROM unified_transactions GROUP BY category"
        return "Payroll is $5000, which was the highest expense as discussed earlier."

    fake_history = [
        {"sender": "user", "text": "What were our top expenses?"},
        {"sender": "agent", "text": "Payroll was the highest at $5000."},
    ]

    patcher, _ = _stub_pipeline(
        monkeypatch, _capture_llm, history=fake_history, rows=[{"category": "Payroll", "total": 5000}]
    )
    with patcher:
        await rag.answer_with_rag(user_id=1, question="How about Payroll?")

    response_prompt = captured_prompts[1]
    assert "=== CONVERSATION HISTORY ===" in response_prompt
    assert "What were our top expenses?" in response_prompt
    assert "Payroll was the highest" in response_prompt


@pytest.mark.anyio
async def test_no_history_when_empty(monkeypatch):
    """When history is empty, no Conversation history block should appear."""
    captured_prompts = []

    async def _capture_llm(model, prompt: str) -> str:
        captured_prompts.append(prompt)
        if "Generate a SQL query" in prompt:
            return "SELECT user_id, SUM(amount) AS total FROM unified_transactions"
        return "Total spend: $6200."

    patcher, _ = _stub_pipeline(
        monkeypatch, _capture_llm, history=[], rows=[{"total": 6200}]
    )
    with patcher:
        await rag.answer_with_rag(user_id=1, question="Total spend?")

    sql_prompt = captured_prompts[0]
    assert "=== CONVERSATION HISTORY ===" not in sql_prompt


@pytest.mark.anyio
async def test_sql_prompt_requires_user_id_in_projection(monkeypatch):
    """The prompt must state the user_id requirement, since the tool enforces it."""
    captured_prompts = []

    async def _capture_llm(model, prompt: str) -> str:
        captured_prompts.append(prompt)
        return "SELECT user_id, SUM(amount) FROM unified_transactions"

    patcher, _ = _stub_pipeline(monkeypatch, _capture_llm, rows=[{"total": 1}])
    with patcher:
        await rag.answer_with_rag(user_id=1, question="Total?")

    assert "include user_id in the SELECT list" in captured_prompts[0]
